name: Test Windows Audit Script
on: [push, workflow_dispatch]
jobs:
  run-audit-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python Pattern_PC_Compliance_Audit.py
